### ISSUE TITLE
TS-7970, linux-4.9: Wrong polarity of CAN Vreg enable pins

### ISSUE THREAD

**Issue by markh-de** [embeddedTS/linux-tsimx#1]
On the Linux 4.9 branch, the polarity for the Vreg Enable pins for CAN1 and CAN2 is wrong.

_How to reproduce:_
Attach a scope to the CAN_L/H lines of each CAN interface, then enable/disable the `can` interfaces (e.g. oldschool `ifconfig can0/1 up/down`) and you will see the opposite of what is to be expected on the CAN lines:
* `up`: CAN_L/H drop to 0V
* `down`: CAN_L/H jump to CAN idle state, i.e. 2.5V

The reason for this are the DTS `enable-active-high;` statements introduced on the Linux 4.9 branch, but missing on Linux 4.1 (tested OK):
* CAN1: https://github.com/embeddedarm/linux-tsimx/blob/8fa1ea18adb68a0f4eddb92ddf0f4303634fe6fb/arch/arm/boot/dts/imx6qdl-ts7970.dtsi#L123
* CAN2: https://github.com/embeddedarm/linux-tsimx/blob/8fa1ea18adb68a0f4eddb92ddf0f4303634fe6fb/arch/arm/boot/dts/imx6qdl-ts7970.dtsi#L132

I guess the author of these lines was misled by the value `GPIO_ACTIVE_HIGH`, noted one line earlier. The result, however, is an undesired negation of the Vreg's enable line polarity, thus breaking CAN bus functionality.

Do you want me to open a PR (only for CAN, as I can only test those), or would you like to review the code yourselves, maybe also fixing/testing other GPIOs that might have wrong polarity?

Thank you very much for your support. Apart from this (easily fixable) issue, the 4.9 branch works really great on TS-7970.

Best regards,
Mark

**Comment by markfeathers** [comment]
Hi Mark,

Thanks for letting us know.  I just pushed a fix for our various platforms that have a CAN enable pin:
https://github.com/embeddedarm/linux-tsimx/commit/2557fe1830c8290dfefabf74663c27a31c6e78b8

Let us know if you have any other issues.
